deployment:
  replicas: null
logs:
  general:
    level: INFO
    format: json
  access:
    enabled: true
    format: json
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"
experimental:
  plugins:
    enabled: true
    bouncer:
      # renovate: moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.1.16 # To update
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    allowExternalNameServices: true
nodeSelector:
  ingress-ready: 'true'
ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik
service:
  annotations:
    'cni.projectcalico.org/ipAddrs': '["10.0.100.1"]'
  loadBalancerIP: 10.0.100.1
ports:
  websecure:
    http3:
      enabled: true
    middlewares:
      - traefik-system@kubernetescrd
  web:
    middlewares:
      - traefik-system@kubernetescrd
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    effect: NoSchedule
  - effect: PreferNoSchedule
    key: node-role.kubernetes.io
    value: master
autoscaling:
  enabled: true
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
