- name: Setup | Apt Update/Upgrade
  ansible.builtin.apt:
    update_cache: "yes"
    upgrade: "yes"
    autoclean: "yes"
    autoremove: "yes"
    state: "latest"
  changed_when: true
- name: Setup | install required packages
  ansible.builtin.apt:
    state: 'present'
    update_cache: true
    pkg:
      - bind9-utils
      - python3-kubernetes
