- name: Setup | Get Helm GPG
  ansible.builtin.shell: |
    curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
  register: helmgpg
- name: Setup | Check to see if helm gpg exists
  ansible.builtin.stat:
    path: "/usr/share/keyrings/helm.gpg"
  register: helm_gpg_file
- name: Setup | Add Helm GPG to system
  become: true
  ansible.builtin.shell: |
    echo "{{ helmgpg.stdout }}" | sudo gpg --dearmor -o /usr/share/keyrings/helm.gpg
  # when: not helm_gpg_file.stat.exists
  changed_when: true
- name: Setup | Add Helm apt source
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    state: present
- name: Setup | Apt Update/Upgrade
  ansible.builtin.apt:
    update_cache: "yes"
    upgrade: "yes"
    autoclean: "yes"
    autoremove: "yes"
    state: "latest"
  changed_when: true
- name: Setup | install required packages
  ansible.builtin.apt:
    state: 'present'
    update_cache: true
    pkg:
    - helm
    - bind9-utils
    - python3-kubernetes
