deployment:
  replicas: null
logs:
  general:
    level: INFO
    format: json
  access:
    enabled: true
    format: json
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"
experimental:
  plugins:
    # enabled: true
    bouncer:
      # renovate: moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.3.1 # To update
    # kubernetesGateway:
    #   enabled: true
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    allowExternalNameServices: true
# nodeSelector:
#   ingress-ready: 'true'
ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik
service:
  annotations:
    cni.projectcalico.org/ipAddrs: '["10.0.100.1"]'
    metallb.universe.tf/address-pool: "system"
  spec:
    loadBalancerIP: 10.0.100.1
    externalTrafficPolicy: Cluster
ports:
  websecure:
    http3:
      enabled: true
    middlewares:
      - network-system@kubernetescrd
  web:
    middlewares:
      - network-system@kubernetescrd
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    effect: NoSchedule
  - effect: PreferNoSchedule
    key: node-role.kubernetes.io
    value: master
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
