global:
  affinity:
    podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - external-secrets
                topologyKey: "kubernetes.io/hostname"
installCRDs: true
replicaCount: 3
leaderElect: true
serviceMonitor:
  enabled: false
webhook:
  serviceMonitor:
    enabled: false
certController:
  serviceMonitor:
    enabled: false
metrics:
  service:
    enabled: false
podDisruptionBudget:
  enabled: true
  minAvailable: 1
