# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: crowdsec-bouncer
#   namespace: network-system
# spec:
#   plugin:
#     bouncer:
#       enabled: true
#       crowdsecMode: stream
#       crowdsecLapiScheme: https
#       crowdsecLapiHost: crowdsec-service.network-system.svc.cluster.local:8080
#       crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/crowdsec-certs/ca.crt
#       crowdsecLapiTLSCertificateBouncerFile: /etc/traefik/crowdsec-certs/tls.crt
#       crowdsecLapiTLSCertificateBouncerKeyFile: /etc/traefik/crowdsec-certs/tls.key
