- name: Check for kubeconfig
  run_once: true
  ansible.builtin.stat:
    path: "{{ home }}/.kube/config"
  register: kubeconfig
- name: Add External Secrets repository
  when: kubeconfig.stat.exists
  kubernetes.core.helm_repository:
    kubeconfig: "{{ home }}/.kube/config"
    name: external-secrets
    repo_url: https://charts.external-secrets.io
- name: Deploy External-Secrets chart
  when: kubeconfig.stat.exists
  kubernetes.core.helm:
    # renovate: registryUrl=https://charts.external-secrets.io
    kubeconfig: "{{ home }}/.kube/config"
    name: external-secrets
    release_namespace: kube-system
    chart_ref: external-secrets
    chart_version: 0.20.3
    chart_repo_url: https://charts.external-secrets.io
    values:
      global:
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - external-secrets
                topologyKey: "kubernetes.io/hostname"
      installCRDs: true
      replicaCount: 3
      leaderElect: true
      serviceMonitor:
        enabled: false
      webhook:
        replicaCount: 3
        port: 443
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        serviceMonitor:
          enabled: false
      certController:
        serviceMonitor:
          enabled: false
      metrics:
        service:
          enabled: false
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
- name: Wait for external-secrets to complete
  kubernetes.core.k8s_info:
    kubeconfig: "{{ home }}/.kube/config"
    kind: Deployment
    namespace: kube-system
    label_selectors:
      - app.kubernetes.io/name = external-secrets
    wait: true
    wait_condition:
      type: "Available"
      status: "True"
    wait_sleep: 30
    wait_timeout: 600
  register: externalsecretsstatus
  until: externalsecretsstatus.resources[0].status.readyReplicas | int > 0
  retries: 20
  delay: 15
