- name: Check for kubeconfig
  delegate_to: localhost
  run_once: true
  ansible.builtin.stat:
    path: "{{ home }}/.kube/config"
  register: kubeconfig
- name: Flux pre-checks
  ansible.builtin.command: |
    flux check --pre
  environment:
    KUBECONFIG: "{{ kubeconfig.stat.path }}"
  become: true
  register: flux_precheck_out
  changed_when: true
  failed_when:
    - flux_precheck_out.rc != 0
- name: Check github secrets encrypted file
  ansible.builtin.stat:
    path: "{{ playbook_dir + '/secrets/github.sops.yaml.enc' }}"
  register: githubsecretsfile
- name: Unencrypt Github Secrets
  ansible.builtin.set_fact:
    github: "{{ lookup('file', playbook_dir + '/secrets/github.sops.yaml.enc') | community.sops.decrypt | ansible.builtin.from_yaml }}"
  when: githubsecretsfile.stat.exists
  failed_when: not githubsecretsfile.stat.exists
- name: Flux bootstrap
  environment:
    GITHUB_TOKEN: "{{ (github | from_yaml).GITHUB_TOKEN }}"
    KUBECONFIG: "{{ kubeconfig.stat.path }}"
  ansible.builtin.command: |
    flux bootstrap github \
      --owner=ryanheyser \
      --repository=homelab-ops \
      --branch=main \
      --private=false \
      --network-policy=false \
      --token-auth=false \
      --reconcile \
      --force
  register: flux_bootstrap_out
  changed_when: true
  failed_when:
    - flux_bootstrap_out.rc != 0
